module.exports = {
  erpHome: [
    {
      type: 'autogenerated', 
      dirName: 'erp-home'
    }
  ],
  purchase: [
    'purchase/overview',
    'purchase/vat-management',
    'purchase/localization-overview',
    {
      type: 'category',
      label: 'Localizations',
      collapsible: true,
      collapsed: false,
      items: [
        'purchase/italy-vat-reporting',
        'purchase/switzerland-vat',
      ],
    },
  ],
  configurations: [
    {
      type: 'autogenerated', 
      dirName: 'configurations'
    }
  ],
  guide: [
    {
      type: 'autogenerated', 
      dirName: 'guide'
    }
  ],
  applications: [
    {
      type: 'autogenerated', 
      dirName: 'applications'
    }
    ], 
};
