module.exports = { 
  erpHome: [
    {
      type: 'autogenerated', 
      dirName: 'erp-home'
    }
  ],
  purchase: [
    {
      type: 'autogenerated', 
      dirName: 'purchase'
    },
    'purchase/extra',
    'purchase/purchase-extra-test',
  ],
  configurations: [
    {
      type: 'autogenerated', 
      dirName: 'configurations'
    }
  ],
  guide: [
    {
      type: 'autogenerated', 
      dirName: 'guide'
    }
  ],
  applications: [
    {
      type: 'autogenerated', 
      dirName: 'applications'
    }
  ], 
};