trigger:
  event: "Issue Updated"
  condition:
    field: "Audio IT"
    value_contains: "- [x] (To do)"        # Verifică dacă "To do" a fost bifat
    or:
      value_contains: "- [x] (In progress)"  # Verifică dacă "In progress" a fost bifat
    or:
      value_contains: "- [x] (Done)"        # Verifică dacă "Done" a fost bifat

actions:
  - updateField:
      project: "test ro"
      field: "Audio IT"
      value: "To do"
      condition:
        description_contains: "- [x] (To do)"  # Dacă "To do" a fost bifat
  
  - updateField:
      project: "test ro"
      field: "Audio IT"
      value: "In progress"
      condition:
        description_contains: "- [x] (In progress)"  # Dacă "In progress" a fost bifat

  - updateField:
      project: "test ro"
      field: "Audio IT"
      value: "Done"
      condition:
        description_contains: "- [x] (Done)"  # Dacă "Done" a fost bifat
