name: Update Audio IT Field in Project

on:
  workflow_dispatch:
    inputs:
      item-id:
        description: 'ID-ul elementului din proiect (project item ID)'
        required: true
      field-value:
        description: 'Valoarea câmpului Audio IT (To do, In progress, Done)'
        required: true
        default: 'In progress'

jobs:
  update-field:
    runs-on: ubuntu-latest

    steps:
      - name: Update Audio IT field
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fieldValueMap = {
              "To do": "685e784f",
              "In progress": "6fb89e71",
              "Done": "23df36af"
            };

            const fieldValue = fieldValueMap[${{ github.event.inputs.field-value }}];

            if (!fieldValue) {
              throw new Error("Invalid value for Audio IT field.");
            }

            await github.graphql(`
              mutation($input: UpdateProjectV2ItemFieldValueInput!) {
                updateProjectV2ItemFieldValue(input: $input) {
                  projectV2Item {
                    id
                  }
                }
              }
            `, {
              input: {
                projectId: "PVT_kwHOCmDFmc4A31rN",  # ID-ul proiectului
                itemId: "${{ github.event.inputs.item-id }}",  # ID-ul itemului
                fieldId: "PVTSSF_lAHOCmDFmc4A31rNzgs6G5E",  # ID-ul câmpului „Audio IT”
                value: {
                  singleSelectOptionId: fieldValue  # Valoarea selectată
                }
              }
            });
