name: Update Audio IT field
on:
  workflow_dispatch:
    inputs:
      itemId:
        description: 'Item ID'
        required: true
      audioITStatus:
        description: 'Audio IT Status (To do, In progress, Done)'
        required: true

jobs:
  update-audio-it:
    runs-on: ubuntu-latest
    steps:
      - name: Set field option ID
        id: map
        run: |
          case "${{ github.event.inputs.audioITStatus }}" in
            "To do")
              echo "OPTION_ID=685e784f" >> $GITHUB_OUTPUT
              ;;
            "In progress")
              echo "OPTION_ID=6fb89e71" >> $GITHUB_OUTPUT
              ;;
            "Done")
              echo "OPTION_ID=23df36af" >> $GITHUB_OUTPUT
              ;;
            *)
              echo "Invalid audioITStatus value"
              exit 1
              ;;
          esac

      - name: Update Audio IT field
        uses: peter-evans/update-project-fields@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          project-id: PVT_kwHOCmDFmc4A31rN
          item-id: ${{ github.event.inputs.itemId }}
          field-id: PVTSSF_lAHOCmDFmc4A31rNzgs6G5E
          option-id: ${{ steps.map.outputs.OPTION_ID }}
