name: Sync Checklist with Project Board

on:
  issues:
    types: [edited]

jobs:
  update-project-column:
    runs-on: ubuntu-latest
    steps:
      - name: Check issue body and update project column
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue.body || "";
            const issue_number = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // Mapare checklist -> status proiect
            let status = null;
            if (/\[x\]\s*\(Done\)/i.test(body)) {
              status = "Done";
            } else if (/\[x\]\s*\(In progress\)/i.test(body)) {
              status = "In progress";
            } else if (/\[x\]\s*\(To do\)/i.test(body)) {
              status = "To do";
            }

            if (!status) {
              console.log("No checklist status detected.");
              return;
            }

            // Caută proiectele asociate cu issue-ul
            const projects = await github.rest.projects.listForRepo({
              owner,
              repo
            });

            // (Aici presupunem că e doar un proiect - altfel ar trebui filtrat după nume)
            const project = projects.data[0];

            // Obține coloanele proiectului
            const columns = await github.rest.projects.listColumns({
              project_id: project.id
            });

            const targetColumn = columns.data.find(col => col.name.toLowerCase() === status.toLowerCase());

            if (!targetColumn) {
              console.log(`No column found for status "${status}"`);
              return;
            }

            // Obține cardurile (ca să găsim cardul care corespunde issue-ului)
            for (const column of columns.data) {
              const cards = await github.rest.projects.listCards({
                column_id: column.id
              });

              for (const card of cards.data) {
                if (card.content_url && card.content_url.includes(`/issues/${issue_number}`)) {
                  // Mută cardul
                  await github.rest.projects.moveCard({
                    card_id: card.id,
                    column_id: targetColumn.id,
                    position: "top"
                  });
                  console.log(`Moved issue #${issue_number} to column "${status}"`);
                  return;
                }
              }
            }

            console.log(`No card found for issue #${issue_number}`);
